### ISSUE TITLE
Publishing to PyPI/Working with the original project

### ISSUE THREAD

**Issue by LyesSaadi** [GradienceTeam/material-color-utilities-python#1]
Hello,

Just an issue to continue the discussion in https://github.com/GradienceTeam/Gradience/pull/118.

This fork doesn't add much more than setting up poetry and improving performances, so it wouldn't be problematic to either merge it upstream, or take up the project.

Gradience has two options to be able to use this project :
1. Include it as a subproject.
2. Publish it to PyPI.

The second option would be preferable for packaging (although, the first doesn't make it impossible either, just, way harder).

**Comment by 0xMRTT** [comment]
You can join the matrix room and ask @aviroblox (in matrix),the creator of the port

**Comment by 0xMRTT** [comment]
https://pypi.org/project/material-color-utilities-python/#description
